/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jeongtae_com_myservice_JNI */

#ifndef _Included_jeongtae_com_myservice_JNI
#define _Included_jeongtae_com_myservice_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jeongtae_com_myservice_JNI
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jeongtae_com_myservice_JNI_plus
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jeongtae_com_myservice_JNI
 * Method:    minus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jeongtae_com_myservice_JNI_minus
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jeongtae_com_myservice_JNI
 * Method:    multiple
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jeongtae_com_myservice_JNI_multiple
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jeongtae_com_myservice_JNI
 * Method:    divide
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jeongtae_com_myservice_JNI_divide
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
